package com.learning.cqrs.user_service.models;

import javax.validation.Valid;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "users")
public class User {
	//an id is already autogenerated in mongo db by default
	@Id
	private String id;
	
	@NotEmpty(message = "First Name is mandatory")
	private String firstName;
	
	@NotEmpty(message = "Last Name is mandatory")
	private String lastName;
	
	@Email(message = "Please Provide valid email")
	private String email;
	
	@Valid
	@NotNull(message = "Account Details are mandatory")
	private Account account;
}
