package com.starwarsuniverse.oauthserver.models;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "users")
public class User {
	//an id is already autogenerated in mongo db by default
	@Id
	private String id;
	
	private String firstName;
	
	private String lastName;
	
	private String email;

	@OneToOne(mappedBy = "user" , cascade = CascadeType.ALL)
	private Account account;
}
