package com.learning.cqrs.user_service.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "users")
public class User {
	//an id is already autogenerated in mongo db by default
	@Id
	private String id;
	
	private String firstName;
	
	private String lastName;
	
	private String email;
	
	private Account account;
}
